//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jermismo.Photo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jermismo.Photo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view information about Pictomaphone.
        /// </summary>
        public static string AboutDesc {
            get {
                return ResourceManager.GetString("AboutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Page.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustments.
        /// </summary>
        public static string AdjustmentsMenuName {
            get {
                return ResourceManager.GetString("AdjustmentsMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying Changes....
        /// </summary>
        public static string ApplyingChangesText {
            get {
                return ResourceManager.GetString("ApplyingChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blurs the image.
        /// </summary>
        public static string BlurDesc {
            get {
                return ResourceManager.GetString("BlurDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur.
        /// </summary>
        public static string BlurTitle {
            get {
                return ResourceManager.GetString("BlurTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to performs a box blur on the image.
        /// </summary>
        public static string BoxBlurDesc {
            get {
                return ResourceManager.GetString("BoxBlurDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Blur.
        /// </summary>
        public static string BoxBlurTitle {
            get {
                return ResourceManager.GetString("BoxBlurTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a vintage filter.
        /// </summary>
        public static string BrawnyDesc {
            get {
                return ResourceManager.GetString("BrawnyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brawny.
        /// </summary>
        public static string BrawnyTitle {
            get {
                return ResourceManager.GetString("BrawnyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjust the brightness and contrast of the image.
        /// </summary>
        public static string BrightnessContrastDesc {
            get {
                return ResourceManager.GetString("BrightnessContrastDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness + Contrast.
        /// </summary>
        public static string BrightnessContrastTitle {
            get {
                return ResourceManager.GetString("BrightnessContrastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjust the red, blue and green channels.
        /// </summary>
        public static string ChannelMixerDesc {
            get {
                return ResourceManager.GetString("ChannelMixerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Mixer.
        /// </summary>
        public static string ChannelMixerTitle {
            get {
                return ResourceManager.GetString("ChannelMixerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to increases contrast using a channel from the image.
        /// </summary>
        public static string ChannelOverlayDesc {
            get {
                return ResourceManager.GetString("ChannelOverlayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Overlay.
        /// </summary>
        public static string ChannelOverlayTitle {
            get {
                return ResourceManager.GetString("ChannelOverlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjust the color balance of the image.
        /// </summary>
        public static string ColorBalanceDesc {
            get {
                return ResourceManager.GetString("ColorBalanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Balance.
        /// </summary>
        public static string ColorBalanceTitle {
            get {
                return ResourceManager.GetString("ColorBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply a colored filter to the image.
        /// </summary>
        public static string ColorFilterDesc {
            get {
                return ResourceManager.GetString("ColorFilterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Filter.
        /// </summary>
        public static string ColorFilterTitle {
            get {
                return ResourceManager.GetString("ColorFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert the image to have one tone.
        /// </summary>
        public static string ColorizeDesc {
            get {
                return ResourceManager.GetString("ColorizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize.
        /// </summary>
        public static string ColorizeTitle {
            get {
                return ResourceManager.GetString("ColorizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a vintage filter.
        /// </summary>
        public static string CountryDesc {
            get {
                return ResourceManager.GetString("CountryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryTitle {
            get {
                return ResourceManager.GetString("CountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crops the image to the selected size.
        /// </summary>
        public static string CropDesc {
            get {
                return ResourceManager.GetString("CropDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Image.
        /// </summary>
        public static string CropTitle {
            get {
                return ResourceManager.GetString("CropTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creates a cross processed image.
        /// </summary>
        public static string CrossProcessDesc {
            get {
                return ResourceManager.GetString("CrossProcessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Process.
        /// </summary>
        public static string CrossProcessTitle {
            get {
                return ResourceManager.GetString("CrossProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adds a dreamy glow to the image.
        /// </summary>
        public static string DreamyGlowDesc {
            get {
                return ResourceManager.GetString("DreamyGlowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dreamy Glow.
        /// </summary>
        public static string DreamyGlowTitle {
            get {
                return ResourceManager.GetString("DreamyGlowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string EffectsMenuName {
            get {
                return ResourceManager.GetString("EffectsMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File + Edit.
        /// </summary>
        public static string FileEditMenuName {
            get {
                return ResourceManager.GetString("FileEditMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string FiltersMenuName {
            get {
                return ResourceManager.GetString("FiltersMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creates a frosted glass feel.
        /// </summary>
        public static string FrostedGlassDesc {
            get {
                return ResourceManager.GetString("FrostedGlassDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frosted Glass.
        /// </summary>
        public static string FrostedGlassTitle {
            get {
                return ResourceManager.GetString("FrostedGlassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blurs the image.
        /// </summary>
        public static string GaussianBlurDesc {
            get {
                return ResourceManager.GetString("GaussianBlurDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian Blur.
        /// </summary>
        public static string GaussianBlurTitle {
            get {
                return ResourceManager.GetString("GaussianBlurTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert the image to black and white.
        /// </summary>
        public static string GrayscaleDesc {
            get {
                return ResourceManager.GetString("GrayscaleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        public static string GrayscaleTitle {
            get {
                return ResourceManager.GetString("GrayscaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjust the hue, saturation and lightness.
        /// </summary>
        public static string HueSaturationDesc {
            get {
                return ResourceManager.GetString("HueSaturationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue + Saturation.
        /// </summary>
        public static string HueSaturationTitle {
            get {
                return ResourceManager.GetString("HueSaturationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageMenuName {
            get {
                return ResourceManager.GetString("ImageMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjust the lows, mids and highs.
        /// </summary>
        public static string LevelsDesc {
            get {
                return ResourceManager.GetString("LevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string LevelsTitle {
            get {
                return ResourceManager.GetString("LevelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simulates vintage Lomo camera.
        /// </summary>
        public static string LomoDesc {
            get {
                return ResourceManager.GetString("LomoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lomo.
        /// </summary>
        public static string LomoTitle {
            get {
                return ResourceManager.GetString("LomoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This image has no Exif Data.
        /// </summary>
        public static string MissingExifMessage {
            get {
                return ResourceManager.GetString("MissingExifMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Exif.
        /// </summary>
        public static string MissingExifTitle {
            get {
                return ResourceManager.GetString("MissingExifTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a negative of the image.
        /// </summary>
        public static string NegativeDesc {
            get {
                return ResourceManager.GetString("NegativeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string NegativeTitle {
            get {
                return ResourceManager.GetString("NegativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t do effects when there isn&apos;t an image. Open something..
        /// </summary>
        public static string NoImageOpenMessage {
            get {
                return ResourceManager.GetString("NoImageOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheesh!.
        /// </summary>
        public static string NoImageOpenTitle {
            get {
                return ResourceManager.GetString("NoImageOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a vintage filter.
        /// </summary>
        public static string OldNewYorkDesc {
            get {
                return ResourceManager.GetString("OldNewYorkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old New York.
        /// </summary>
        public static string OldNewYorkTitle {
            get {
                return ResourceManager.GetString("OldNewYorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenButtonText {
            get {
                return ResourceManager.GetString("OpenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open a photo from the photo library.
        /// </summary>
        public static string OpenPhotoDesc {
            get {
                return ResourceManager.GetString("OpenPhotoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected image could not be opened..
        /// </summary>
        public static string OpenPhotoError {
            get {
                return ResourceManager.GetString("OpenPhotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Photo.
        /// </summary>
        public static string OpenPhotoTitle {
            get {
                return ResourceManager.GetString("OpenPhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reduces the bit-depth of the image.
        /// </summary>
        public static string PosterizeDesc {
            get {
                return ResourceManager.GetString("PosterizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posterize.
        /// </summary>
        public static string PosterizeTitle {
            get {
                return ResourceManager.GetString("PosterizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view the photo full-screen with gesture support.
        /// </summary>
        public static string PreviewButtonDesc {
            get {
                return ResourceManager.GetString("PreviewButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview the Photo.
        /// </summary>
        public static string PreviewButtonTitle {
            get {
                return ResourceManager.GetString("PreviewButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resizes the image.
        /// </summary>
        public static string ResizeDesc {
            get {
                return ResourceManager.GetString("ResizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Image.
        /// </summary>
        public static string ResizeTitle {
            get {
                return ResourceManager.GetString("ResizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revert to last save.
        /// </summary>
        public static string RevertDesc {
            get {
                return ResourceManager.GetString("RevertDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will lose any changes you&apos;ve made..
        /// </summary>
        public static string RevertMessageMessage {
            get {
                return ResourceManager.GetString("RevertMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string RevertMessageTitle {
            get {
                return ResourceManager.GetString("RevertMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string RevertTitle {
            get {
                return ResourceManager.GetString("RevertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate or flip the photo.
        /// </summary>
        public static string RotateFlipDesc {
            get {
                return ResourceManager.GetString("RotateFlipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate / Flip.
        /// </summary>
        public static string RotateFlipTitle {
            get {
                return ResourceManager.GetString("RotateFlipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with that name already exists. Do you want to overwrite it?.
        /// </summary>
        public static string SaveFileOverwriteMessage {
            get {
                return ResourceManager.GetString("SaveFileOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string SaveFileOverwriteTitle {
            get {
                return ResourceManager.GetString("SaveFileOverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save your photo to the photo library.
        /// </summary>
        public static string SavePhotoDesc {
            get {
                return ResourceManager.GetString("SavePhotoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh, I had a problem saving the image:.
        /// </summary>
        public static string SavePhotoErrorMessage {
            get {
                return ResourceManager.GetString("SavePhotoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I take it you&apos;d like to save this to the Saved Photos Library..
        /// </summary>
        public static string SavePhotoMessageText {
            get {
                return ResourceManager.GetString("SavePhotoMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        public static string SavePhotoMessageTitle {
            get {
                return ResourceManager.GetString("SavePhotoMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I saved your image!.
        /// </summary>
        public static string SavePhotoSuccessMessage {
            get {
                return ResourceManager.GetString("SavePhotoSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huzzah!.
        /// </summary>
        public static string SavePhotoSuccessTitle {
            get {
                return ResourceManager.GetString("SavePhotoSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your Photo.
        /// </summary>
        public static string SavePhotoTitle {
            get {
                return ResourceManager.GetString("SavePhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert the image to sepia tone.
        /// </summary>
        public static string SepiaDesc {
            get {
                return ResourceManager.GetString("SepiaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepia.
        /// </summary>
        public static string SepiaTitle {
            get {
                return ResourceManager.GetString("SepiaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change App Settings.
        /// </summary>
        public static string SettingsDesc {
            get {
                return ResourceManager.GetString("SettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareButtonText {
            get {
                return ResourceManager.GetString("ShareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solarize the image.
        /// </summary>
        public static string SolarizeDesc {
            get {
                return ResourceManager.GetString("SolarizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solarize.
        /// </summary>
        public static string SolarizeTitle {
            get {
                return ResourceManager.GetString("SolarizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a square border to the image.
        /// </summary>
        public static string SquareBorderDesc {
            get {
                return ResourceManager.GetString("SquareBorderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Border.
        /// </summary>
        public static string SquareBorderTitle {
            get {
                return ResourceManager.GetString("SquareBorderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bright greens like summer in a deep forest.
        /// </summary>
        public static string SummerForestDesc {
            get {
                return ResourceManager.GetString("SummerForestDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer Forest.
        /// </summary>
        public static string SummerForestTitle {
            get {
                return ResourceManager.GetString("SummerForestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a vintage filter.
        /// </summary>
        public static string SundayMorningDesc {
            get {
                return ResourceManager.GetString("SundayMorningDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday Morning.
        /// </summary>
        public static string SundayMorningTitle {
            get {
                return ResourceManager.GetString("SundayMorningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        public static string TakeButtonText {
            get {
                return ResourceManager.GetString("TakeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take a photo using the camera app.
        /// </summary>
        public static string TakePhotoDesc {
            get {
                return ResourceManager.GetString("TakePhotoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Photo.
        /// </summary>
        public static string TakePhotoTitle {
            get {
                return ResourceManager.GetString("TakePhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjust the temperature and tone.
        /// </summary>
        public static string TemperatureToneDesc {
            get {
                return ResourceManager.GetString("TemperatureToneDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature + Tone.
        /// </summary>
        public static string TemperatureToneTitle {
            get {
                return ResourceManager.GetString("TemperatureToneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creates a tilt shift effect.
        /// </summary>
        public static string TiltShiftDesc {
            get {
                return ResourceManager.GetString("TiltShiftDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Shift.
        /// </summary>
        public static string TiltShiftTitle {
            get {
                return ResourceManager.GetString("TiltShiftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simulates Velvia film.
        /// </summary>
        public static string VelvianDesc {
            get {
                return ResourceManager.GetString("VelvianDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velvian.
        /// </summary>
        public static string VelvianTitle {
            get {
                return ResourceManager.GetString("VelvianTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjust the vibrance of colors.
        /// </summary>
        public static string VibranceDesc {
            get {
                return ResourceManager.GetString("VibranceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrance.
        /// </summary>
        public static string VibranceTitle {
            get {
                return ResourceManager.GetString("VibranceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view the images exif data.
        /// </summary>
        public static string ViewExifDesc {
            get {
                return ResourceManager.GetString("ViewExifDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Exif Data.
        /// </summary>
        public static string ViewExifTitle {
            get {
                return ResourceManager.GetString("ViewExifTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adds a vignette to the image.
        /// </summary>
        public static string VignetteDesc {
            get {
                return ResourceManager.GetString("VignetteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vignette.
        /// </summary>
        public static string VignetteTitle {
            get {
                return ResourceManager.GetString("VignetteTitle", resourceCulture);
            }
        }
    }
}
